### ISSUE TITLE
Add rules to the game

### ISSUE THREAD

**Issue by jenjaminbones** [jenjaminbones/qgame#1]
There are two main rules to enforce:
* After the initial relabelling stage, the player can only do swaps that are between adjacent nodes on the architecture.
* A player cannot continue to the next gate until the current one is on the hardware.

Warning messages could be added if they fail to do this?

**Comment by jenjaminbones** [comment]
For the demo (demo branch) I added a couple of lines to not allow a player to move on if the current gate is not on the hardware.

**Comment by tomjbell** [comment]
Yeah i've done the same thing on my branch.

**Comment by tomjbell** [comment]
I think these are sorted now
